title: Sergio Manzanero
subtitle: Sergio Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  Sergio Manzanero, Developer y soñador

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Inicio
      url: /
    - text: Sobre mí
      url: /sobre-mi
    - text: Blog
      url: /blog
    - text: Servicios
      url : /servicios
    - text: Contacto
      url : /contacto
    

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Sergio Manzanero
author_bio: Trabajando por un mundo mejor. Realización de proyectos sociales. Participo en Colonias Felinas :D
author_email: "manzanero.sergio@gmail.com"
author_location: España
author_website_url: "https://singletontechs.com"
typewrite-text: devlopr y soñador
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: ARSYS - IONOS CLOUD
              company_logo: asrsys.jpg
              company_url: https://www.arsys.es
              designation: Ingeniero preventa
              description: <li type="square">Recopilación de datos de los clientes para la elaboración de soluciones técnicas a medida para todo tipo de clientes y potenciales clientes. </li>
                           <li type="square">Responsable del apoyo técnico al desarrollo de ventas de productos y servicios de la unidad de IONOS CLOUD y todas las actividades de ventas relacionados con clientes estratégicos. </li>
                           <li type="square">Dando respuesta a las solicitudes comerciales en los sectores privado y público.</li>
                           <li type="square">Desarrollo planes de negocios, objetivos a largo plazo, estrategia de precios y metas de satisfacción del cliente, realizando un seguimiento de fabricantes.</li>
              visibility: true
            - company_name: GRUPO SERMICRO
              company_logo: sermicro.jpg
              company_url: https://gruposermicro.com
              designation: Desarrollador, Administrador de Sistemas y DEVOPS
              description: <li type="square">Programación en SQL, PHP, Script Shell de UNIX, Python y Java. </li>
                            <li type="square">Creación y migración de webs con Wordpress, Joomla, Drupal y PrestaShop.</li>
                            <li type="square">Securización y optimización de servidores para entornos productivos Linux/Aix/HP-UX</li>
                            <li type="square">Realización de scripts de carga de datos en bases de datos MySql, SQL Server y Oracle.</li>
                            <li type="square">Migración de Sistemas Windows Server y Linux</li>
                            <li type="square">Actualización de versiones software y mantenimiento preventivo de entornos productivos. Windows, Linux y Aix.</li>
                            <li type="square">Montaje y configuración de equipos físicos para virtualizaciones con VMware ESXi</li>
                            <li type="square">Conexión stretched cluster de dos equipos en dos regiones</li>
                            <li type="square">Creación de DRP y DR</li>
                            <li type="square">Administración de diversos sistemas de backups </li>
                            <li type="square">Creación de servicios API Rest</li>
                            <li type="square">Instalaciones y configuración de Jira  y Jenkins</li>
                            <li type="square">Automatización de procesos CI/DI con Gitlab  </li>
                            <li type="square">Programación modelo vista controlador en Joomla!</li>
                            <li type="square">Parametrización y optimización de las bases de datos anteriormente descritas.</li>
                            <li type="square">Tareas administrativas y toma de requerimiento en clientes para la implantación de soluciones profesionales avanzadas. </li>
                            <li type="square">Parametrización y optimización de sistemas. Windows, Linux y Aix.</li>
                            <li type="square">Clasificación y resolución de incidencias con diversas herramientas de ticketing.</li>
                            <li type="square">Creación de procedimiento para el Derecho al Olvido con Alfresco. Linux</li>
                            <li type="square">Configuraciones de VPN.</li>
                            <li type="square">Configuraciones de DNS.</li>
                            <li type="square">Análisis de diseños de sistemas, base de datos y vulnerabilidades.</li>
                            <li type="square">Auditorías de Seguridad.</li>
                            <li type="square">Configuraciones de NAS Synology.</li>
              visibility: true

# Education
author_education_details:
              - college_logo: logoIESA.jpg
                college_name: IES Augustóbriga
                college_url: https://iesaugustobriga.educarex.es/
                college_degree: Desarrollo de Aplicaciones Multiplataforma
                description: DAM
                visibility: true
              - college_logo: licenciados.png
                college_name: Licenciados Reunidos
                college_url: https://www.licenciadosreunidos.es/
                college_degree: EGG
                description: 
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

github_username:  sergiomanzanero

# contact form - (choose formspress or getform)
getform_endpoint: 58eb2070-e5c7-4f9f-adca-bca7e5dfd2d5
#formspree_email: manzanero.sergio@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
# show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: false

defaults:
  -
    scope:
      path: "servicos"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
