baseURL: "https://sergiomanzanero.github.ip"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/sergiomanzanero/sergiomanzanero/sergiocms"
paginate: 4
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
