baseURL: "https://sergiomanzanero.github.io/sergiocms"
languageCode: "es-es"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/sergiomanzanero/sergiomanzanero.github.io/tree/main/sergiocms"
paginate: 4
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
